Data-Drive-System-master/Data-Drive-System-master/drive_system/drive_system/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('file_manager.urls')),

]

Data-Drive-System-master/Data-Drive-System-master/drive_system/file_manager/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('file_list/', views.file_list, name='file_list'),
    path('create_folder/', views.create_folder, name='create_folder'),
    path('create_file/', views.create_file, name='create_file'),
    path('update_file/<int:file_id>/', views.update_file, name='update_file'),
    path('update_folder/<int:folder_id>/', views.update_folder, name='update_folder'),
    path('delete_folder/<int:folder_id>/', views.delete_folder, name='delete_folder'),
    path('delete_file/<int:file_id>/', views.delete_file, name='delete_file'),

]

Data-Drive-System-master/Data-Drive-System-master/drive_system/file_manager/models.py
from django.db import models
from django.contrib.auth.models import User

class Folder(models.Model):
    name = models.CharField(max_length=255, default="untitled Folder")
    parent_folder = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)

    def update_name(self, new_name):
        self.name = new_name
        self.save()

class File(models.Model):
    name = models.CharField(max_length=255, default="untitled Folder")
    parent_folder = models.ForeignKey(Folder, null=True, blank=True, on_delete=models.CASCADE)
    file = models.FileField(upload_to='uploads/', default=False)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name

Data-Drive-System-master/Data-Drive-System-master/drive_system/file_manager/forms.py
from django import forms
from .models import Folder, File
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
class FolderForm(forms.ModelForm):
    class Meta:
        model = Folder
        fields = ['name', 'parent_folder']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Enter folder name (optional)'}),
        }
    # directory = forms.FileField(widget=forms.ClearableFileInput(attrs={'webkitdirectory': 'true'}))

class FileForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ['name', 'parent_folder', 'file']

class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User  # Assuming you have imported User from django.contrib.auth.models
        fields = ['username', 'password1', 'password2']

Data-Drive-System-master/Data-Drive-System-master/drive_system/file_manager/views.py
from django.views.decorators.csrf import csrf_protect, csrf_exempt
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect, get_object_or_404
from .models import Folder, File
from .forms import FolderForm, FileForm, UserRegistrationForm

@login_required
def file_list(request):
    folders = Folder.objects.filter(parent_folder=None)
    files = File.objects.filter(parent_folder=None)
    return render(request, 'file_manager/file_list.html', {'folders': folders, 'files': files})

@login_required
def create_folder(request):
    if request.method == 'POST':
        form = FolderForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data.get('name', 'Untitled Folder')
            parent_folder = form.cleaned_data.get('parent_folder', None)
            parent_folder_id = parent_folder.id if parent_folder else None
            folder = Folder(name=name, parent_folder_id=parent_folder_id)
            folder.save()
            messages.success(request, 'Folder created successfully!')
            return redirect('file_list')
    else:
        form = FolderForm()
    return render(request, 'file_manager/create_folder.html', {'form': form})

@login_required
def update_folder(request, folder_id):
    folder = get_object_or_404(Folder, id=folder_id)
    if request.method == 'POST':
        new_name = request.POST['new_name']
        folder.update_name(new_name)
        messages.success(request, 'Folder name updated successfully!')
        return redirect('file_list')
    return render(request, 'file_manager/update_folder.html', {'folder': folder})

@login_required
def create_file(request):
    if request.method == 'POST':
        form = FileForm(request.POST, request.FILES)
        if form.is_valid():
            file = form.save(commit=False)
            file.owner = request.user
            file.save()
            messages.success(request, 'File uploaded successfully!')
            return redirect('file_list')
    else:
        form = FileForm()
    return render(request, 'file_manager/create_file.html', {'form': form})

@login_required
def update_file(request, file_id):
    file = get_object_or_404(File, id=file_id)
    if request.method == 'POST':
        form = FileForm(request.POST, request.FILES, instance=file)
        if form.is_valid():
            form.save()
            messages.success(request, 'File updated successfully!')
            return redirect('file_list')
    else:
        form = FileForm(instance=file)

    return render(request, 'file_manager/update_file.html', {'form': form, 'file': file})


def delete_folder(request, folder_id):
    folder = get_object_or_404(Folder, id=folder_id)
    if request.method == 'POST':
        folder.delete()
        messages.success(request, 'Folder deleted successfully!')
        return redirect('file_list')
    return render(request, 'file_manager/delete_folder.html', {'folder': folder})

def delete_file(request, file_id):
    file = get_object_or_404(File, id=file_id)
    if request.method == 'POST':
        file.delete()
        messages.success(request, 'File deleted successfully!')
        return redirect('file_list')
    return render(request, 'file_manager/delete_file.html', {'file': file})

@csrf_exempt
def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('file_list') 

    else:
        form = UserRegistrationForm()

    return render(request, 'registration/register.html', {'form': form})

@csrf_exempt
def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('file_list')  # Redirect to the file_list view after login

    else:
        form = AuthenticationForm()

    return render(request, 'registration/login.html', {'form': form})

def user_logout(request):
    logout(request)
    return redirect('login')

Data-Drive-System-master/Data-Drive-System-master/drive_system/file_manager/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}File Drive{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Data Drive System</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item me-2">
                    <a class="nav-link" href="{% url 'create_folder' %}">Create Folder</a>
                  </li>
                  <li class="nav-item me-2">
                    <a class="nav-link" href="{% url 'create_file' %}">Create File</a>
                  </li>
                  <li class="nav-item ">
                    <a class="nav-link" href="{% url 'file_list' %}">File List</a>
                  </li>
                </ul>

                <ul class=" d-flex navbar-nav mb-2 mb-lg-0">

                      <li class="nav-item me-3">
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                      </li>
                      
                      <li class="nav-item me-3">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                      </li>

                      {% if user.is_authenticated %}
                      <li class="nav-item me-3">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                      </li>
                      {% endif %}
                  
                    </ul>
              </div>
            </div>
          </nav>
    </header>
    <main>
        <div class="container">
            <h1>{% block content_title %}{% endblock %}</h1>
            {% block content %}
            {% endblock %}
        </div>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

Data-Drive-System-master/Data-Drive-System-master/drive_system/file_manager/templates/file_manager/create_file.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create File</title>
    <link rel="stylesheet" href="{% static 'file_manager.css' %}">
</head>
<body>
    <h1>Create File</h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="name">File Name:</label>
        <input type="text" id="name" name="name" required>
        <label for="parent_folder">Select Folder:</label>
        <select id="parent_folder" name="parent_folder">
            <option value="">None</option>
            {% for folder in folders %}
                <option value="{{ folder.id }}">{{ folder.name }}</option>
            {% endfor %}
        </select>
        <label for="file">Upload File:</label>
        <input type="file" id="file" name="file" required>
        <button type="submit">Upload File</button>
    </form>
    <hr>
    <a type="submit" href="{% url 'create_folder' %}" class="btn btn-primary">Create Folder</a>
    <a type="button" href="{% url 'file_list' %}" class="btn btn-success">File List</a>
</body>
</html>
{%endblock%}

Data-Drive-System-master/Data-Drive-System-master/drive_system/file_manager/templates/file_manager/create_folder.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Folder</title>
    <link rel="stylesheet" href="{% static 'file_manager.css' %}">
</head>
<body>
    <h1>Create Folder</h1>
    <div class="content">
    {% comment %} <form method="post">
        {% csrf_token %}
        <label for="name">Folder Name:</label>
        <input type="text" id="name" name="name" required>
        <label for="parent_folder">Parent Folder (Optional):</label>
        <select id="parent_folder" name="parent_folder">
            <option value="">None</option>
            {% for folder in folders %}
                <option value="{{ folder.id }}">{{ folder.name }}</option>
            {% endfor %}
        </select>
        <button type="submit">Create Folder</button>
    </form> {% endcomment %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create Folder">
    </form>
    </div>
    <hr>
    <a href="{% url 'file_list' %}" class="btn btn-primary">File List</a>
    <a href="{% url 'create_file' %}" class="btn btn-success">Create File</a>
</body>
</html>
{% endblock %}

Data-Drive-System-master/Data-Drive-System-master/drive_system/file_manager/templates/file_manager/delete_file.html
{% extends "base.html" %}
{% block content %}
<h2>Delete File</h2>
<p>Are you sure you want to delete the file "{{ file.name }}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Delete</button>
</form>
<a href="{% url 'file_list' %}">Cancel</a>
{% endblock %}

Data-Drive-System-master/Data-Drive-System-master/drive_system/file_manager/templates/file_manager/delete_folder.html
{% extends "base.html" %}
{% block content %}
<h2>Delete Folder</h2>
<p>Are you sure you want to delete the folder "{{ folder.name }}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Delete</button>
</form>
<a href="{% url 'file_list' %}">Cancel</a>
{% endblock %}

Data-Drive-System-master/Data-Drive-System-master/drive_system/file_manager/templates/file_manager/file_list.html
{% extends "base.html" %}
{% block content %}
<h1>File Manager</h1>
<hr>

<h2>Folders</h2>
<ul>
    {% for folder in folders %}
        <li>
            {{ folder.name }}
            <a href="{% url 'update_folder' folder.id %}">Edit</a>
            <a href="{% url 'delete_folder' folder.id %}">Delete</a>
            <hr>
            <ul>
                {% for subfolder in folder.folder_set.all %}
                    <li>
                        {{ subfolder.name }}
                        <a href="{% url 'update_folder' subfolder.id %}">Edit</a>
                        <a href="{% url 'delete_folder' subfolder.id %}">Delete</a>
                    </li>
                {% endfor %}
            </ul>
        </li>
    {% endfor %}
</ul>

<h2>Files</h2>
<ul>
    {% for file in files %}
        <li>
            {{ file.name }}
            <a href="{% url 'update_file' file.id %}">Edit</a>
            <a href="{% url 'delete_file' file.id %}">Delete</a>
        </li>
    {% endfor %}
</ul>
<hr>
<a href="{% url 'create_folder' %}" class="btn btn-primary">Create Folder</a>
<a href="{% url 'create_file' %}" class="btn btn-success">Create File</a>

{% endblock %}

Data-Drive-System-master/Data-Drive-System-master/drive_system/file_manager/templates/file_manager/update_file.html
{% extends "base.html" %}
{% block content %}
<h2>Update File</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update File</button>
</form>
<hr>
<a href="{% url 'file_list' %}" class="btn btn-primary">File List</a>
{% endblock %}

Data-Drive-System-master/Data-Drive-System-master/drive_system/file_manager/templates/file_manager/update_folder.html
{% extends "base.html" %}
{% block content %}
<h2>Update Folder Name</h2>
<form method="post">
    {% csrf_token %}
    <label for="new_name">New Folder Name:</label>
    <input type="text" id="new_name" name="new_name" value="{{ folder.name }}" required>
    <button type="submit">Update Name</button>
</form>
<a href="{% url 'file_list' %}">Cancel</a>
{% endblock %}